In [1]:
import pandas as pd

df = pd.read_csv('players_20.csv')
#set Index
df.set_index('short_name',inplace=True)
df

,sofifa_id,player_url,long_name,age,dob,height_cm,weight_kg,nationality,club,overall,...,lwb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb
short_name,,,,,,,,,,,,,,,,,,,,,
L. Messi,158023,https://sofifa.com/player/158023/lionel-messi/...,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona,94,...,68+2,66+2,66+2,66+2,68+2,63+2,52+2,52+2,52+2,63+2
Cristiano Ronaldo,20801,https://sofifa.com/player/20801/c-ronaldo-dos-...,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus,93,...,65+3,61+3,61+3,61+3,65+3,61+3,53+3,53+3,53+3,61+3
Neymar Jr,190871,https://sofifa.com/player/190871/neymar-da-sil...,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain,92,...,66+3,61+3,61+3,61+3,66+3,61+3,46+3,46+3,46+3,61+3
J. Oblak,200389,https://sofifa.com/player/200389/jan-oblak/20/...,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid,91,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
E. Hazard,183277,https://sofifa.com/player/183277/eden-hazard/2...,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid,91,...,66+3,63+3,63+3,63+3,66+3,61+3,49+3,49+3,49+3,61+3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Shao Shuai,245006,https://sofifa.com/player/245006/shuai-shao/20...,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC,48,...,43+2,42+2,42+2,42+2,43+2,45+2,46+2,46+2,46+2,45+2
Xiao Mingjie,250995,https://sofifa.com/player/250995/mingjie-xiao/...,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC,48,...,44+2,43+2,43+2,43+2,44+2,46+2,47+2,47+2,47+2,46+2
Zhang Wei,252332,https://sofifa.com/player/252332/wei-zhang/20/...,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC,48,...,47+2,49+2,49+2,49+2,47+2,47+2,49+2,49+2,49+2,47+2
Wang Haijian,251110,https://sofifa.com/player/251110/haijian-wang/...,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC,48,...,48+2,48+2,48+2,48+2,48+2,48+2,49+2,49+2,49+2,48+2
Pan Ximing,233449,https://sofifa.com/player/233449/ximing-pan/20...,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC,48,...,48+2,49+2,49+2,49+2,48+2,48+2,50+2,50+2,50+2,48+2

In [2]:
# select columns
df = df[['long_name', 'age', 'dob', 'height_cm', 'weight_kg', 'nationality', 'club']]
df

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC
Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

In [3]:
#Get all data about L.Messi
df.loc['L. Messi']

long_name      Lionel Andrés Messi Cuccittini
age                                        32
dob                                1987-06-24
height_cm                                 170
weight_kg                                  72
nationality                         Argentina
club                             FC Barcelona
Name: L. Messi, dtype: object

In [4]:
#Get the heught of Messi
df.loc['L. Messi','height_cm']

np.int64(170)

In [5]:
#Get all rows insife the heught column
df.loc[:,'height_cm']

short_name
L. Messi             170
Cristiano Ronaldo    187
Neymar Jr            175
J. Oblak             188
E. Hazard            175
                    ...
Shao Shuai           186
Xiao Mingjie         177
Zhang Wei            186
Wang Haijian         185
Pan Ximing           182
Name: height_cm, Length: 18278, dtype: int64

In [6]:
#Get all data about L.Messi and Cristiano Ronaldo
df.loc[['L. Messi','Cristiano Ronaldo']]

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus

In [7]:
players=['L. Messi','Cristiano Ronaldo']

df.loc[players,'age':'club']

,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,
L. Messi,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,34,1985-02-05,187,83,Portugal,Juventus

## Set a new value to one cell

In [8]:
#update the hight of L. Messi
df.loc['L. Messi','height_cm'] =175

In [9]:
#show to dataFrame
df

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,175,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC
Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

In [10]:
#set height of all player to 190
df.loc[:,'height_cm'] =190
df

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,190,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,190,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,190,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,190,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,190,74,Belgium,Real Madrid
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,190,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,190,66,China PR,Shanghai SIPG FC
Zhang Wei,张威,19,2000-05-16,190,75,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18,2000-08-02,190,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,潘喜明,26,1993-01-11,190,78,China PR,Hebei China Fortune FC

## Drop Rows OR Columns

In [11]:
#Drop one row
df.drop('L. Messi',axis=0)

#Drop tow or more rows
df.drop(['L. Messi','Cristiano Ronaldo'],axis=0)

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,190,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,190,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,190,74,Belgium,Real Madrid
K. De Bruyne,Kevin De Bruyne,28,1991-06-28,190,70,Belgium,Manchester City
M. ter Stegen,Marc-André ter Stegen,27,1992-04-30,190,85,Germany,FC Barcelona
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,190,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,190,66,China PR,Shanghai SIPG FC
Zhang Wei,张威,19,2000-05-16,190,75,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18,2000-08-02,190,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,潘喜明,26,1993-01-11,190,78,China PR,Hebei China Fortune FC

In [12]:
#Drop one col
df.drop('long_name',axis=1)
#drop the last col
df.drop(df.columns[[-1]],axis=1)

#Drop tow or more cols
df.drop(['long_name','dob'],axis=1)

,age,height_cm,weight_kg,nationality,club
short_name,,,,,
L. Messi,32,190,72,Argentina,FC Barcelona
Cristiano Ronaldo,34,190,83,Portugal,Juventus
Neymar Jr,27,190,68,Brazil,Paris Saint-Germain
J. Oblak,26,190,87,Slovenia,Atlético Madrid
E. Hazard,28,190,74,Belgium,Real Madrid
...,...,...,...,...,...
Shao Shuai,22,190,79,China PR,Beijing Renhe FC
Xiao Mingjie,22,190,66,China PR,Shanghai SIPG FC
Zhang Wei,19,190,75,China PR,Hebei China Fortune FC
Wang Haijian,18,190,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,26,190,78,China PR,Hebei China Fortune FC

## Create a Random Sample

In [13]:
# Extract 10 random elemnts from the nationality col
df['nationality'].sample(10)

short_name
J. Swift                       England
J. Cavallaro                 Argentina
N. Spolli                    Argentina
U. Bapoh                       Germany
Kim Tae Han             Korea Republic
E. Barreto                    Paraguay
Yohan Tavares                 Portugal
Iñigo Martínez                   Spain
D. Herazo                     Colombia
A. Barman         United Arab Emirates
Name: nationality, dtype: object

In [14]:
#Random 20% form df
df.sample(frac=0.2,random_state=1)

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
D. Cvetinović,Dušan Cvetinović,30,1988-12-24,190,79,Serbia,Yokohama F. Marinos
M. Silva,Marcelo Silva,30,1989-03-21,190,82,Uruguay,Real Salt Lake
S. Mandash,Sultan Ahmed Mandash,24,1994-10-17,190,63,Saudi Arabia,Al Ahli
I. Gruev,Ilia Gruev,19,2000-05-06,190,74,Bulgaria,SV Werder Bremen
Kangin Lee,이강인 Kangin Lee,18,2001-02-19,190,61,Korea Republic,Valencia CF
...,...,...,...,...,...,...,...
P. Finger,Patrick Finger,18,2001-01-01,190,61,Germany,Eintracht Frankfurt
T. Băluță,Tudor Băluță,20,1999-03-27,190,80,Romania,Brighton & Hove Albion
Adrián Maideira,Adrián Guto Maideira Almeida,35,1984-02-29,190,66,Brazil,Goiás
Choi Chul Soon,최철순 崔喆淳,32,1987-02-08,190,68,Korea Republic,Jeonbuk Hyundai Motors
K. Agard,Kieran Agard,29,1989-10-10,190,67,England,Milton Keynes Dons

In [15]:
#avec reptition
df.sample(frac=0.2,replace=True,random_state=1)

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
Josué Chiamulera,Josué Durval Chiamulera Vaz,27,1992-02-29,190,80,Brazil,Grêmio
A. Gündüz,Atakan Gündüz,18,2001-01-01,190,84,Turkey,Trabzonspor
L. Sadiku,Loret Sadiku,27,1991-07-28,190,70,Kosovo,Kasimpaşa SK
M. Leverbe,Maxime Leverbe,22,1997-02-15,190,76,France,Chievo Verona
S. Ichazo,Salvador Ichazo,27,1992-01-26,190,83,Uruguay,Torino
...,...,...,...,...,...,...,...
T. Vollnhofer,Thomas Vollnhofer,34,1984-09-02,190,75,Austria,SKN St. Pölten
V. Demaku,Vesel Demaku,19,2000-02-05,190,68,Austria,FK Austria Wien
D. Dudziński,Daniel Dudziński,17,2002-03-07,190,72,Poland,Zagłębie Lubin
M. Saito,齋藤 学,29,1990-04-04,190,68,Japan,Kawasaki Frontale
Z. Touré,Zargo Touré,29,1989-11-11,190,79,Senegal,Gençlerbirliği SK

## Filter with query()

In [16]:
#select player older than34 
df.query("age>=34")

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,190,83,Portugal,Juventus
G. Chiellini,Giorgio Chiellini,34,1984-08-14,190,85,Italy,Juventus
S. Handanovič,Samir Handanovič,34,1984-07-14,190,92,Slovenia,Inter
Fernandinho,Fernando Luiz Rosa,34,1985-05-04,190,67,Brazil,Manchester City
Thiago Silva,Thiago Emiliano da Silva,34,1984-09-22,190,82,Brazil,Paris Saint-Germain
...,...,...,...,...,...,...,...
N. Hunt,Nicky Hunt,35,1983-09-03,190,86,England,Crewe Alexandra
K. Ogi,荻 晃太,36,1983-05-05,190,76,Japan,Vissel Kobe
J. McCombe,Jamie McCombe,36,1983-01-01,190,79,England,Lincoln City
G. Maley,Gary Maley,36,1982-08-03,190,90,Scotland,Livingston FC
Zhou Ting,周挺,40,1979-02-05,190,73,China PR,Dalian YiFang FC

In [17]:
#select players older than 34 from Italy
df.query("age>=34 and nationality=='Italy' ")

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
G. Chiellini,Giorgio Chiellini,34,1984-08-14,190,85,Italy,Juventus
G. Buffon,Gianluigi Buffon,41,1978-01-28,190,92,Italy,Juventus
F. Quagliarella,Fabio Quagliarella,36,1983-01-31,190,79,Italy,Sampdoria
D. De Rossi,Daniele De Rossi,35,1983-07-24,190,83,Italy,Boca Juniors
M. Parolo,Marco Parolo,34,1985-01-25,190,75,Italy,Lazio
A. Mirante,Antonio Mirante,35,1983-07-08,190,79,Italy,Roma
A. Diamanti,Alessandro Diamanti,36,1983-05-02,190,75,Italy,Western United FC
L. Rigoni,Luca Rigoni,34,1984-12-07,190,75,Italy,Parma
E. Giaccherini,Emanuele Giaccherini,34,1985-05-05,190,60,Italy,Chievo Verona
C. Maggio,Christian Maggio,37,1982-02-11,190,79,Italy,Benevento
F. Magnanelli,Francesco Magnanelli,34,1984-11-12,190,79,Italy,Sassuolo
D. Dainelli,Dario Dainelli,40,1979-06-09,190,78,Italy,Livorno
F. Marchetti,Federico Marchetti,36,1983-02-07,190,83,Italy,Genoa
F. Peluso,Federico Peluso,35,1984-01-20,190,82,Italy,Sassuolo
L. Rossettini,Luca Rossettini,34,1985-05-09,190,82,Italy,Lecce
C. Terzi,Claudio Terzi,35,1984-06-19,190,69,Italy,Spezia
G. Pazzini,Giampaolo Pazzini,34,1984-08-02,190,78,Italy,Hellas Verona
A. Rosina,Alessandro Rosina,35,1984-01-31,190,69,Italy,US Salernitana 1919
D. Maietta,Domenico Maietta,36,1982-08-03,190,75,Italy,Empoli
A. Cordaz,Alex Cordaz,36,1983-01-01,190,83,Italy,Crotone
S. Floccari,Sergio Floccari,37,1981-11-12,190,79,Italy,SPAL
M. Iori,Manuel Iori,37,1982-03-12,190,72,Italy,Cittadella
M. Stefani,Mirco Stefani,35,1984-01-25,190,80,Italy,Pordenone
A. Matri,Alessandro Matri,34,1984-08-19,190,80,Italy,Sassuolo
G. Pegolo,Gianluca Pegolo,38,1981-03-25,190,76,Italy,Sassuolo
D. Gastaldello,Daniele Gastaldello,36,1983-06-25,190,77,Italy,Brescia
D. Moscardelli,Davide Moscardelli,39,1980-02-03,190,80,Italy,Pisa
E. Calaiò,Emanuele Calaiò,37,1982-01-08,190,75,Italy,US Salernitana 1919
A. Luci,Andrea Luci,34,1985-03-30,190,68,Italy,Livorno
M. Agazzi,Michael Agazzi,34,1984-07-03,190,80,Italy,US Cremonese
D. Croce,Daniele Croce,36,1982-09-09,190,70,Italy,US Cremonese
A. Rosati,Antonio Rosati,36,1983-06-26,190,88,Italy,Torino
M. Gazzola,Marcello Gazzola,34,1985-04-03,190,77,Italy,Parma
F. Mazzeo,Fabio Mazzeo,35,1983-07-24,190,77,Italy,Livorno
M. De Agostini,Michele De Agostini,35,1983-11-27,190,78,Italy,Pordenone
A. Pomini,Alberto Pomini,38,1981-03-17,190,80,Italy,Venezia FC
F. Evacuo,Felice Evacuo,36,1982-08-23,190,88,Italy,Trapani
G. Munari,Gianni Munari,36,1983-06-24,190,84,Italy,Parma
L. Pagliarulo,Luca Pagliarulo,35,1984-02-29,190,80,Italy,Trapani
M. Troiano,Michele Troiano,34,1985-01-07,190,82,Italy,Ascoli
F. Piovaccari,Federico Piovaccari,34,1984-09-01,190,77,Italy,Rayo Vallecano
C. Del Grosso,Cristiano Del Grosso,36,1983-03-24,190,66,Italy,Pescara
G. Masucci,Gaetano Masucci,34,1984-10-26,190,72,Italy,Pisa
R. Vitiello,Roberto Vitiello,36,1983-05-08,190,72,Italy,Castellammare di Stabia
D. Bassi,Davide Bassi,34,1985-04-12,190,83,Italy,Spezia
A. Bruno,Alessandro Bruno,35,1983-07-04,190,70,Italy,Pescara
T. Berni,Tommaso Berni,36,1983-03-06,190,80,Italy,Inter
M. Mancosu,Matteo Mancosu,34,1984-12-22,190,75,Italy,Virtus Entella
P. Gori,Pier Graziano Gori,39,1980-05-10,190,83,Italy,Benevento
S. Farelli,Simone Farelli,36,1983-02-19,190,82,Italy,Pescara

In [18]:
#Add not oprator to the first query
df.query("not(age>=34)")

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,190,72,Argentina,FC Barcelona
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,190,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,190,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,190,74,Belgium,Real Madrid
K. De Bruyne,Kevin De Bruyne,28,1991-06-28,190,70,Belgium,Manchester City
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,190,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,190,66,China PR,Shanghai SIPG FC
Zhang Wei,张威,19,2000-05-16,190,75,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18,2000-08-02,190,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,潘喜明,26,1993-01-11,190,78,China PR,Hebei China Fortune FC

In [19]:
#convert height to meters and select those with height above 1.8
df.query("height_cm/100>1.8")

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,190,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,190,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,190,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,190,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,190,74,Belgium,Real Madrid
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,190,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,190,66,China PR,Shanghai SIPG FC
Zhang Wei,张威,19,2000-05-16,190,75,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18,2000-08-02,190,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,潘喜明,26,1993-01-11,190,78,China PR,Hebei China Fortune FC

In [20]:
#select players that were born after 1990

#check out data types
df.dtypes
#conver 'dob' col datetime type
df['dob'] = df['dob'].astype('datetime64[ns]')

#query

df.query('dob.dt.year >1990')

C:\Users\DELL\AppData\Local\Temp\ipykernel_13092\2692716788.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['dob'] = df['dob'].astype('datetime64[ns]')

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,190,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,190,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,190,74,Belgium,Real Madrid
K. De Bruyne,Kevin De Bruyne,28,1991-06-28,190,70,Belgium,Manchester City
M. ter Stegen,Marc-André ter Stegen,27,1992-04-30,190,85,Germany,FC Barcelona
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,190,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,190,66,China PR,Shanghai SIPG FC
Zhang Wei,张威,19,2000-05-16,190,75,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18,2000-08-02,190,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,潘喜明,26,1993-01-11,190,78,China PR,Hebei China Fortune FC

#### Aplly method

In [21]:
#use numpy fun and apply it to series
import numpy as np
df['age'].apply(np.sqrt)

short_name
L. Messi             5.656854
Cristiano Ronaldo    5.830952
Neymar Jr            5.196152
J. Oblak             5.099020
E. Hazard            5.291503
                       ...
Shao Shuai           4.690416
Xiao Mingjie         4.690416
Zhang Wei            4.358899
Wang Haijian         4.242641
Pan Ximing           5.099020
Name: age, Length: 18278, dtype: float64

In [22]:
#creat your own fun and apply it to  a data frame
def calc_bmi(row):
    return row['weight_kg']/(row['height_cm']/100)**2
df.apply(calc_bmi,axis=1)

short_name
L. Messi             19.944598
Cristiano Ronaldo    22.991690
Neymar Jr            18.836565
J. Oblak             24.099723
E. Hazard            20.498615
                       ...
Shao Shuai           21.883657
Xiao Mingjie         18.282548
Zhang Wei            20.775623
Wang Haijian         20.498615
Pan Ximing           21.606648
Length: 18278, dtype: float64

## Lambda fun

In [23]:
#lambda fun one line
sum_lambda = lambda a,b:a+b

sum_lambda(2,3)

5

In [24]:
df['height_cm'].apply(lambda x:x/100)

short_name
L. Messi             1.9
Cristiano Ronaldo    1.9
Neymar Jr            1.9
J. Oblak             1.9
E. Hazard            1.9
                    ...
Shao Shuai           1.9
Xiao Mingjie         1.9
Zhang Wei            1.9
Wang Haijian         1.9
Pan Ximing           1.9
Name: height_cm, Length: 18278, dtype: float64

In [25]:
df['long_name'].apply(lambda x:x.upper())

short_name
L. Messi                  LIONEL ANDRÉS MESSI CUCCITTINI
Cristiano Ronaldo    CRISTIANO RONALDO DOS SANTOS AVEIRO
Neymar Jr                  NEYMAR DA SILVA SANTOS JUNIOR
J. Oblak                                       JAN OBLAK
E. Hazard                                    EDEN HAZARD
                                    ...
Shao Shuai                                            邵帅
Xiao Mingjie                                MINGJIE XIAO
Zhang Wei                                             张威
Wang Haijian                                         汪海健
Pan Ximing                                           潘喜明
Name: long_name, Length: 18278, dtype: object

In [26]:
df['dob'].apply(lambda x:x.month)

short_name
L. Messi             6
Cristiano Ronaldo    2
Neymar Jr            2
J. Oblak             1
E. Hazard            1
                    ..
Shao Shuai           3
Xiao Mingjie         1
Zhang Wei            5
Wang Haijian         8
Pan Ximing           1
Name: dob, Length: 18278, dtype: int64

### Copy

In [ ]:
df.copy() #this is not rolated

df.copy(deep=False) #rolated

### Pivot Table